### ISSUE TITLE
Egg texture limits the mipmap level

### ISSUE THREAD

**Issue by mezz** [PenguinSquad/Harvest-Festival#10]
`textures/models/egg.png` is 8x8 pixels, which is smaller than the minimum required 16x16. 
This limits the mipmap level of the texture atlas, leading to ugly artifacts in distant textures.
Please make this texture 16x16 to fix this issue for BTM.

**Comment by Yulife** [comment]
Oh it does? I thought increments in 2 were okay, things like 24x24, 6x6, etc not. I'll change it :)
