### ISSUE TITLE
Fatigue and Exhaustion Potion Effect Icons

### ISSUE THREAD

**Issue by joshiejack** [PenguinSquad/Harvest-Festival#12]
These two need effect icons, you can find the template in gui/potions

They can be whatever you like, but the difference is pretty much the first is this guy
http://www.sherv.net/cm/emoticons/yellow-face/tired-smiley-emoticon.png

Aka just tired.

While the second is almost this guy
https://cdn.shopify.com/s/files/1/1061/1924/products/sleepy-emoji-pillow_1024x1024.jpg?v=1458743258
But more like this https://airamara.files.wordpress.com/2009/12/exhaustion.jpg

Aka you when keep blinking, can barely stay awake.

You can make them whatever you like fits best for these emotions.

**Comment by Yulife** [comment]
Wait i thohght we removed that

**Comment by joshiejack** [comment]
No, we removed stamina and fatigue for food, these are potion effects that get added when you do a bunch of farm work while hungry.

**Comment by Yulife** [comment]
So not like a HUD bar? But potion effects? :s

**Comment by joshiejack** [comment]
Yes, Like the vanilla ones in here http://i.imgur.com/vAHL7TO.png

(in this file https://github.com/PenguinSquad/Harvest-Festival/blob/master/src/main/resources/assets/harvestfestival/textures/gui/potions.png)
